name: Build and push to staging branch

on:
  push:
    branches:
      - main  # Triggers the workflow on each push to the 'main' branch.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
            
      - name: Install Dependencies
        run: |
          npm install
          npm run build

      - name: Push to Staging
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Menggunakan token GitHub bawaan
        run: |
          git config --global user.email "yusfiwawan2@gmail.com"
          git config --global user.name "xrafffcode"
          git add .
          git commit -m "Deploy to Staging"
          git push origin main:staging
