name: Build and push to staging branch

on:
  push:
    branches:
      - main  # Triggers the workflow on each push to the 'main' branch.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
            
      - name: Install Dependencies
        run: |
          npm install
          npm run build

      - name: Create Staging Branch
        run: |
          git checkout -b staging
          git push -u origin staging
